---
title: "Ex 1 :"
author: "Nohalito"
date: "2025-11-27"
output: html_document
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

packages <- c("readxl", "moments", "ggplot2", "fitdistrplus", "evd", "extRemes",
              "copula", "PerformanceAnalytics", "tseries")
lapply(packages, require, character.only = TRUE)
```
## 1°/ Data extraction :

```{r data, include = FALSE}
data = read_excel('../datasets/capm.xls', skip = 1)

data$Date <- as.Date(data$Date, origin = "1899-12-30")

# Construct excess returns 
asset <- "MICROSOFT"

# Excess returns
date <- data$Date
asset_excess  <- log(cbind(data[[asset]] - data$USTB3M))
market_excess <- log(cbind(data$SANDP - data$USTB3M))

# Remove NA
df <- na.omit(data.frame(date, asset_excess, market_excess))

head(data)
```

```{r}
# Basic stats
summary(df)

# Moments
apply(df[2:3], 2, skewness)
apply(df[2:3], 2, kurtosis)
```

## 2°/ EDA :
### 2.1°/ Distribution plot (asset excess):

```{r}
# Distribution plot (asset excess)
# Load the necessary library
library(ggplot2)
library(gridExtra)

# First plot (asset excess)
plot1 <- ggplot(df, aes(x = df$asset_excess)) +
  geom_histogram(aes(y = ..density..), bins = 40, fill = "grey") +
  geom_density(color = "blue") +
  ggtitle("Histogram and Density – Asset Excess Returns")

# Second plot (market excess)
plot2 <- ggplot(df, aes(x = df$market_excess)) +
  geom_histogram(aes(y = ..density..), bins = 40, fill = "grey") +
  geom_density(color = "red") +
  ggtitle("Histogram and Density – Market Excess Returns")

# Arrange both plots side-by-side
grid.arrange(plot1, plot2, ncol = 2,widths = c(1, 1))
```

### 2.2°/ QQ-plot :

```{r}
# Touche moi le QQ-plot
plot1 = qqnorm(df$asset_excess) +
  qqline(df$asset_excess, col = "red")

plot2 = qqnorm(df$market_excess) +
  qqline(df$market_excess, col = "red")
```

### 2.3°/ Box-plot :

```{r}
boxplot(df$asset_excess, main = "Boxplot – Asset Excess Returns")
```

### 2.4°/ Time series plot :

```{r}
plot(df$date, df$asset_excess, type = "l",
     main = "Time Series of Asset Excess Returns",
     ylab = "Returns", xlab = "Time")
```

### 2.5°/ ACF :

```{r}
acf(df$asset_excess, main = "ACF – Asset Excess Returns")
```

### 2.6°/ PP-plot :

```{r}
ppplot <- function(x) {
  n <- length(x)
  y <- sort(x)
  p <- pnorm(y, mean(x), sd(x))
  plot((1:n)/(n+1), p, main="PP-Plot")
  abline(0,1,col="red")
}

ppplot(df$asset_excess)
```

### 2.7°/ Bivariate scatterplot :

```{r}
plot(df$market_excess, df$asset_excess,
     xlab = "Market Excess Returns",
     ylab = "Asset Excess Returns",
     main = "Bivariate Scatterplot")
```

## 3°/ Fit an extreme distribution :

```{r}
library(data.table)

# Whatever the distribution, we need positive data => ofc I (don't) listen in class so I missed that part.
df$mo <- strftime(df$date,"%m")
df$yr <- strftime(df$date,"%Y")

indexbis <- df

maxima <- setDT(df)[, .(asset_up = max(df$asset_excess)), by = .(yr, mo)]

x <- df$asset_excess # Should I put '-' before it ?
x <- x[x > 0]  # focus on losses

# We ballin' on Redbull distribution :
fit_weibull <- fitdist(df$asset_excess, "weibull")
summary(fit_weibull)
plot(fit_weibull)
```

## 4°/ Fit the GEV distribution :

```{r}
#install.packages("fExtremes")
#library('fExtremes')
#?fgev
#gev_fit <- fgev(df$asset_excess)
#summary(gev_fit)

# Fuck it, we rollin' on evd library instead
library(evd)

fit_gev_asset<-fevd(as.vector(df$asset_excess), method = "MLE", type="GEV")
plot(fit_gev_asset)
summary(fit_gev_asset, silent=FALSE) #to get the standard error of estimates


gev_fit <- fgev(df$asset_excess)
summary(gev_fit)

```

### 4.1°/ GEV QQ-plot :

```{r}
# Extract fitted parameters
params <- gev_fit$estimate

# Compute the theoretical quantiles from the fitted GEV distribution
theoretical_quantiles <- qgev(ppoints(length(df$asset_excess)), loc = params[1], scale = params[2], shape = params[3])

# Create the QQ plot manually
qqplot(theoretical_quantiles, df$asset_excess)
```

### 4.2°/ GEV Density :

```{r}
plot(gev_fit)
```

### 4.3°/ GEV Probability

```{r}
plot(gev_fit)
```

## 5 : Elliptical copulas :
```{r}
u_asset  <- rank(df$asset_excess)/(nrow(df)+1)
u_market <- rank(df$market_excess)/(nrow(df)+1)

U <- cbind(u_asset, u_market)
```
```{r}
#install.packages("copula")
#install.packages("gsl")
#library(gsl)
#library(copula)
#installed.packages()
#search()
#install.packages("VineCopula")
#library(VineCopula)

gauss_cop <- normalCopula(dim = 2)
fit_gauss <- fitCopula(gauss_cop, U, method = "ml")
summary(fit_gauss)
```

## 6°/ Archimedean copulas : Clayton :

```{r}
clayton <- claytonCopula(dim = 2)
fit_clayton <- fitCopula(clayton, U, method = "ml")
summary(fit_clayton)
```

